/* ===== DATA ===== */
let easyWords = [
/* 🐶 CON VẬT */
"con mèo","con chó","con cá","con gà","con vịt","con chim","con heo","con bò","con dê","con ngựa",
"con voi","con hổ","con sư tử","con khỉ","con thỏ","con gấu","con sói","con cáo","con nai","con hươu",
"con rùa","con rắn","con ếch","con cua","con tôm","con cá vàng","con cá mập","con cá heo","con cá ngừ","con cá trê",
"con chim sẻ","con chim én","con chim bồ câu","con chim đại bàng","con chim cú","con chim cánh cụt","con chim công","con chim họa mi","con chim sáo","con chim chích",
"chó con","mèo con","gà con","vịt con","heo con","bò con","dê con","ngựa con","thỏ con","khỉ con",
"đàn cá","đàn chim","bầy chó","bầy mèo","chuồng gà","chuồng vịt","trại bò","trại heo","vườn thú","sở thú",
"nuôi chó","nuôi mèo","nuôi cá","cho ăn","uống nước","chạy nhanh","bay cao","bơi lội","kêu meo","sủa to",

/* 🎨 MÀU SẮC */
"đỏ","xanh","vàng","tím","hồng","đen","trắng","nâu","cam","xám",
"màu đỏ","màu xanh","màu vàng","màu tím","màu hồng","màu đen","màu trắng","màu nâu","màu cam","màu xám",
"xanh lá","xanh dương","xanh đậm","xanh nhạt","đỏ tươi","đỏ đậm","vàng nhạt","vàng đậm","hồng nhạt","hồng đậm",
"màu sáng","màu tối","màu đẹp","màu lạ","màu nhẹ","màu đậm","màu pastel","màu nổi","màu dịu","màu tươi",
"phối màu","tô màu","vẽ màu","chọn màu","trộn màu","màu nước","màu sáp","màu bút","màu đẹp","màu xinh",

/* 🧸 VẬT DỤNG */
"cái bàn","cái ghế","cái bút","cái thước","cái cặp","cái sách","cái vở","cái bảng","cái phấn","cái đèn",
"bàn học","ghế ngồi","bút chì","bút mực","bút màu","thước kẻ","cặp sách","quyển vở","cuốn sách","bảng đen",
"bảng trắng","cục tẩy","hộp bút","cái kéo","cái gọt","cái hộp","cái túi","cái chai","cái ly","cái cốc",
"cái muỗng","cái nĩa","cái đĩa","cái tô","cái nồi","cái chảo","cái bếp","cái tủ","cái giường","cái gối",
"cái mền","cái quạt","cái máy","cái điện thoại","cái tivi","cái máy tính","cái đồng hồ","cái cửa","cái khóa","cái chìa",
"đồ chơi","xe đồ chơi","búp bê","gấu bông","quả bóng","cái diều","cái xe","cái tàu","cái máy bay","cái robot",

/* 👨‍👩‍👧‍👦 GIA ĐÌNH */
"mẹ","ba","bố","má","cha","ông","bà","anh","chị","em",
"ba mẹ","bố mẹ","ông bà","anh em","chị em","gia đình","người thân","họ hàng","cô chú","dì dượng",
"bác trai","bác gái","cậu mợ","ông nội","bà nội","ông ngoại","bà ngoại","anh trai","chị gái","em trai",
"em gái","con cái","cha mẹ","người nhà","cả nhà","gia đình nhỏ","gia đình lớn","gia đình vui","gia đình hạnh phúc","gia đình ấm áp",
"yêu mẹ","yêu ba","kính ông","quý bà","thương anh","mến chị","chơi cùng","ăn cùng","ngủ cùng","học cùng",

/* 🔁 BỔ SUNG MIX (tăng độ đa dạng) */
"đi học","đi chơi","đi ngủ","đi bộ","đi dạo",
"ăn cơm","ăn bánh","ăn cá","ăn rau","ăn trái cây",
"uống nước","uống sữa","uống nước cam","uống nước dừa","uống trà",
"trời nắng","trời mưa","trời lạnh","trời đẹp","trời sáng",
"bé ngoan","bé học","bé chơi","bé ăn","bé ngủ",
"viết chữ","gõ chữ","đọc sách","làm bài","học bài",
"vẽ tranh","tô màu","xếp hình","chơi game","nghe nhạc",
"chạy nhanh","nhảy cao","đứng lên","ngồi xuống","nằm ngủ",

/* 💬 CỤM TỪ CÓ NGHĨA (2-4 TỪ) */
"mẹ nấu cơm","ba đi làm","bé chào mẹ","bé yêu gia đình","ông đọc báo","bà kể chuyện","chị học bài","em chơi bóng",
"cả nhà ăn cơm","mẹ ôm em","ba bế bé","bé giúp mẹ","bé thăm ông bà","anh chơi cùng em","chị dắt em đi","gia đình rất vui",
"bé rửa tay","bé đánh răng","bé rửa mặt","bé chải tóc","bé mang dép","bé mặc áo","bé đội mũ","bé đeo cặp",
"bé ăn sáng","bé uống sữa","bé uống nước","bé ăn trái cây","bé ăn rau xanh","bé đi học","bé đến lớp","bé chào cô",
"bé ngồi ngay ngắn","bé nghe cô giảng","bé đọc bài","bé viết chữ","bé làm bài","bé giơ tay","bé chơi cùng bạn","bé chia đồ chơi",
"bé về nhà","bé cất cặp","bé thay quần áo","bé rửa chân","bé ăn cơm","bé xem tranh","bé đọc sách","bé đi ngủ",
"con mèo ngủ","con chó chạy","con cá bơi","con chim bay","con gà gáy","con vịt bơi","con bò ăn cỏ","con dê leo núi",
"con ngựa chạy nhanh","thỏ ăn cà rốt","con voi rất to","con kiến rất nhỏ","chim hót líu lo","mèo kêu meo meo","chó sủa gâu gâu","cá bơi dưới nước",
"mặt trời mọc","mặt trời sáng","trời xanh trong","mây trắng bay","gió thổi nhẹ","mưa rơi tí tách","cầu vồng rất đẹp","bầu trời đầy sao",
"hoa nở trong vườn","lá cây màu xanh","cây cho bóng mát","cỏ xanh ngoài sân","chim đậu trên cành","bướm bay quanh hoa","ong tìm mật hoa","sông chảy êm đềm",
"quả cam màu vàng","quả táo màu đỏ","quả xoài rất thơm","dưa hấu rất ngọt","bé thích ăn chuối","mẹ mua trái cây","rau xanh tốt lắm","cơm nóng thơm ngon",
"xe chạy trên đường","tàu chạy trên ray","thuyền đi trên sông","máy bay trên trời","xe đạp của bé","bé đá quả bóng","bé thả diều","bé xếp hình",
"hôm nay trời đẹp","buổi sáng thật vui","buổi trưa nắng ấm","buổi chiều mát mẻ","buổi tối yên tĩnh","đêm nay trăng sáng","bé cười thật tươi","bé học thật chăm",
"em yêu mẹ","em yêu ba","em yêu ông bà","em yêu chị","em thương em bé","em quý bạn bè","em yêu trường lớp","em yêu quê hương",
"xin chào buổi sáng","cảm ơn mẹ nhé","con chào ông bà","bé nói cảm ơn","bé biết xin lỗi","bé luôn lễ phép","bé biết nhường bạn","bé chăm ngoan lắm",

/* 🌟 BỔ SUNG NHIỀU CỤM 3-4 TỪ CÓ NGHĨA */
"mẹ đang nấu cơm","ba đang đọc sách","ông đang tưới cây","bà đang quét nhà","chị đang học bài",
"anh đang đá bóng","em đang ngủ ngon","mẹ dắt bé đi","ba đưa bé học","ông kể chuyện vui",
"bà hát cho bé","mẹ mua bánh ngon","ba sửa chiếc xe","chị giúp em học","anh chơi với em",
"bé ôm bà ngoại","bé thăm ông nội","bé chúc mẹ vui","cả nhà đi chơi","cả nhà xem phim",
"gia đình cùng ăn","mẹ gọi bé dậy","ba đón bé về","bé phụ mẹ dọn","bé mang dép bà",
"bé dậy thật sớm","bé gấp chăn gọn","bé mở cửa sổ","bé rửa mặt sạch","bé chải răng sạch",
"bé mặc áo đẹp","bé mang cặp sách","bé chuẩn bị học","bé ăn sáng ngon","bé uống sữa ấm",
"bé chào mọi người","bé bước ra cửa","bé đi học sớm","bé về nhà vui","bé thay áo mới",
"bé rửa tay sạch","bé lau mặt khô","bé xếp dép ngay","bé cất đồ gọn","bé tắm thật sạch",
"bé mặc đồ ngủ","bé lên giường ngủ","bé ngủ thật ngon","bé thức dậy vui","bé tự buộc tóc",
"bé học chữ mới","bé tập viết chữ","bé đọc từng chữ","bé đọc câu ngắn","bé viết thật đẹp",
"bé tô chữ ngay","bé đếm từ một","bé học số mới","bé làm toán vui","bé xem sách tranh",
"bé mở trang sách","bé nghe cô dạy","bé trả lời đúng","bé giơ tay cao","bé ngồi học ngoan",
"bé học cùng cô","bé học cùng mẹ","bé tập gõ phím","bé gõ thật chậm","bé gõ thật đúng",
"bé đọc thành tiếng","bé nhớ bài học","bé làm bài xong","bé cất sách vở","bé chuẩn bị bài",
"bé chào người lớn","bé nói lời hay","bé biết cảm ơn","bé nói xin lỗi","bé biết xin phép",
"bé nhường đồ chơi","bé chia sẻ bánh","bé giúp bạn nhỏ","bé nắm tay bạn","bé chơi thật ngoan",
"bé không chen hàng","bé xếp hàng ngay","bé giữ lời hứa","bé biết chờ đợi","bé nghe lời cô",
"bé nghe lời mẹ","bé nghe lời ba","bé yêu thương em","bé kính trọng ông","bé kính trọng bà",
"bé giữ gìn đồ","bỏ rác đúng chỗ","rửa tay trước ăn","che miệng khi ho","chào khi ra về",
"bé cười rất tươi","bé vui cả ngày","bé thấy thật vui","bé đang rất vui","bé thích món này",
"bé thích màu xanh","bé thích màu hồng","bé thích con mèo","bé thích con chó","bé thương mẹ nhiều",
"bé nhớ ông bà","bé yêu cô giáo","bé quý bạn bè","bé vui khi học","bé vui khi chơi",
"bé bình tĩnh nhé","bé đừng buồn nhé","bé tự tin lên","bé cố gắng nhé","bé làm được rồi",
"con mèo bắt chuột","con chó giữ nhà","con chim làm tổ","con cá quẫy nước","con gà tìm thóc",
"con vịt tìm mồi","con bò kéo xe","con dê ăn cỏ","con ngựa phi nhanh","con thỏ chạy nhanh",
"con khỉ hái quả","con voi uống nước","con hổ đi săn","con sư tử gầm","con rùa bò chậm",
"con ếch nhảy cao","con cua bò ngang","con tôm bơi nhanh","con ong tìm mật","con bướm hút mật",
"con kiến tha mồi","con sóc leo cây","con nai chạy nhanh","con hươu ăn lá","con chim hót vang",
"đàn cá bơi xa","đàn chim bay cao","gà con tìm mẹ","vịt con theo đàn","mèo con nằm ngủ",
"mặt trời lên cao","mặt trời tỏa nắng","bầu trời xanh biếc","mây bay rất chậm","mây trắng trôi xa",
"gió thổi qua cây","gió làm lá bay","mưa rơi ngoài sân","mưa làm đường ướt","cầu vồng bảy sắc",
"trăng tròn rất sáng","trăng soi mặt hồ","sao sáng trên trời","lá rơi ngoài sân","lá xanh trên cành",
"hoa nở rất đẹp","hoa thơm trong vườn","cây cao trước nhà","cây lớn che mát","cỏ mọc xanh rì",
"sông chảy qua làng","suối chảy róc rách","biển xanh rất rộng","sóng vỗ vào bờ","cát vàng dưới chân",
"nắng chiếu qua cửa","sương đọng trên lá","chim bay qua núi","mây phủ trên núi","gió mát buổi chiều",
"cái bàn màu nâu","cái ghế màu xanh","cái cặp của bé","cái bút màu đỏ","cái thước rất dài",
"quyển sách rất đẹp","hộp bút màu hồng","bảng đen trên tường","đèn sáng trong phòng","quạt quay rất nhanh",
"đồng hồ chỉ giờ","cửa sổ đang mở","cánh cửa đang đóng","chiếc giường rất êm","cái gối rất mềm",
"cái mền rất ấm","chiếc ly có nước","cái thìa trên bàn","chiếc đĩa màu trắng","cái nồi trên bếp",
"cái chảo đang nóng","tủ sách nhiều truyện","đồ chơi trong hộp","quả bóng màu xanh","con búp bê đẹp",
"gấu bông rất mềm","chiếc xe đồ chơi","cái diều bay cao","máy bay đồ chơi","robot đang bước đi",
"mẹ nấu canh ngon","mẹ chiên quả trứng","bé ăn cơm nóng","bé ăn canh rau","bé ăn thịt cá",
"bé uống nước ấm","bé uống sữa tươi","bé ăn quả táo","bé ăn quả cam","bé ăn quả chuối",
"bé ăn quả xoài","bé ăn dưa hấu","quả táo rất giòn","quả cam rất ngọt","quả chuối chín vàng",
"quả xoài chín thơm","dưa hấu ruột đỏ","rau xanh rất tốt","cà rốt màu cam","cà chua màu đỏ",
"bánh mì rất thơm","bánh ngọt rất ngon","sữa chua mát lạnh","cơm nóng trên bàn","canh rau rất ngon",
"bé vỗ hai tay","bé giơ hai tay","bé dang hai tay","bé nhắm hai mắt","bé mở hai mắt",
"bé lắc cái đầu","bé xoay cổ nhẹ","bé bước chân đều","bé chạy quanh sân","bé nhảy qua vạch",
"bé đi thật thẳng","bé đứng thật vững","bé ngồi thật ngay","bé cúi người xuống","bé quay người lại",
"bé đưa tay lên","bé hạ tay xuống","bé đá chân nhẹ","bé hít thở sâu","bé tập thể dục",
"bé chơi ngoài sân","bé đi công viên","bé đến trường học","bé vào lớp học","bé ra sân chơi",
"bé đi siêu thị","bé về thăm quê","bé đi sở thú","bé ngắm con voi","bé xem cá bơi",
"bé đi bãi biển","bé xây lâu đài","bé đi trên cát","bé ngắm biển xanh","bé đi cùng mẹ",
"bé đi cùng ba","bé sang thăm bà","bé về cùng chị","bé chơi trong nhà","bé đọc sách hay"
];
