#!/usr/bin/env python3
"""Render toàn bộ easyWords thành MP3 bằng Google Cloud Text-to-Speech.

Output:
- Audio/tts/<sha1-16>.mp3
- tts-manifest.js

Authentication dùng Application Default Credentials (ADC), ví dụ:
    gcloud auth application-default login
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_FILE = ROOT / "data-easy.js"
OUTPUT_DIR = ROOT / "Audio" / "tts"
MANIFEST_FILE = ROOT / "tts-manifest.js"
DEFAULT_VOICE = "vi-VN-Chirp3-HD-Aoede"
DEFAULT_RATE = 0.82


def normalize_text(value: str) -> str:
    return unicodedata.normalize("NFC", str(value)).strip()


def extract_easy_words(path: Path = DATA_FILE) -> list[str]:
    source = path.read_text(encoding="utf-8")
    match = re.search(r"\blet\s+easyWords\s*=\s*\[", source)
    if not match:
        raise RuntimeError("Không tìm thấy mảng easyWords trong data-easy.js")

    start = match.end()
    depth = 1
    i = start
    in_string = False
    escape = False
    quote = ""

    while i < len(source) and depth > 0:
        ch = source[i]
        if in_string:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == quote:
                in_string = False
        else:
            if ch in ('"', "'"):
                in_string = True
                quote = ch
            elif ch == "[":
                depth += 1
            elif ch == "]":
                depth -= 1
                if depth == 0:
                    body = source[start:i]
                    break
        i += 1
    else:
        raise RuntimeError("Mảng easyWords chưa đóng đúng cú pháp")

    # easyWords hiện dùng string JSON double-quote; cách này giữ nguyên Unicode/escape.
    tokens = re.findall(r'"(?:\\.|[^"\\])*"', body)
    words: list[str] = []
    seen: set[str] = set()

    for token in tokens:
        try:
            value = normalize_text(json.loads(token))
        except json.JSONDecodeError:
            continue
        if value and value not in seen:
            seen.add(value)
            words.append(value)

    if not words:
        raise RuntimeError("Không đọc được nội dung easyWords")
    return words


def file_name_for_text(text: str) -> str:
    digest = hashlib.sha1(normalize_text(text).encode("utf-8")).hexdigest()[:16]
    return f"{digest}.mp3"


def load_tts_client():
    try:
        from google.cloud import texttospeech
    except ImportError as exc:
        raise RuntimeError(
            "Thiếu google-cloud-texttospeech. Chạy: py -m pip install -r tools/requirements-tts.txt"
        ) from exc
    return texttospeech, texttospeech.TextToSpeechClient()


def list_voices() -> int:
    texttospeech, client = load_tts_client()
    response = client.list_voices(request={"language_code": "vi-VN"})
    voices = sorted(response.voices, key=lambda voice: voice.name)
    print(f"Tìm thấy {len(voices)} voice vi-VN:\n")
    for voice in voices:
        genders = texttospeech.SsmlVoiceGender
        gender_name = genders(voice.ssml_gender).name if voice.ssml_gender else "UNKNOWN"
        print(f"- {voice.name:<38} {gender_name:<8} {voice.natural_sample_rate_hertz} Hz")
    return 0


def synthesize(client, texttospeech, text: str, voice_name: str, speaking_rate: float) -> bytes:
    request_input = texttospeech.SynthesisInput(text=text)
    voice = texttospeech.VoiceSelectionParams(
        language_code="vi-VN",
        name=voice_name,
    )
    audio_config = texttospeech.AudioConfig(
        audio_encoding=texttospeech.AudioEncoding.MP3,
        speaking_rate=speaking_rate,
    )
    response = client.synthesize_speech(
        input=request_input,
        voice=voice,
        audio_config=audio_config,
    )
    return response.audio_content


def write_manifest(items: list[tuple[str, str]], voice: str, rate: float) -> None:
    mapping = {text: f"Audio/tts/{filename}" for text, filename in items}
    generated_at = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")

    content = (
        "/* AUTO-GENERATED BY tools/render_google_tts.py - DO NOT EDIT BY HAND */\n"
        f"window.GO_CHU_TTS_MANIFEST = Object.freeze({json.dumps(mapping, ensure_ascii=False, indent=2)});\n"
        "window.GO_CHU_TTS_META = Object.freeze({\n"
        "  version: 1,\n"
        "  provider: \"google-cloud-text-to-speech\",\n"
        "  languageCode: \"vi-VN\",\n"
        f"  voice: {json.dumps(voice, ensure_ascii=False)},\n"
        f"  speakingRate: {rate},\n"
        f"  generatedAt: {json.dumps(generated_at)},\n"
        f"  count: {len(mapping)}\n"
        "});\n"
    )
    MANIFEST_FILE.write_text(content, encoding="utf-8", newline="\n")


def render_all(args: argparse.Namespace) -> int:
    if not 0.25 <= args.speaking_rate <= 2.0:
        raise RuntimeError("--speaking-rate phải nằm trong khoảng 0.25 đến 2.0")

    words = extract_easy_words()
    if args.only:
        wanted = {normalize_text(value) for value in args.only}
        words = [word for word in words if word in wanted]
    if args.limit:
        words = words[: args.limit]

    print(f"Nguồn: {DATA_FILE.name}")
    print(f"Số câu duy nhất: {len(words)}")
    print(f"Voice: {args.voice}")
    print(f"Speaking rate: {args.speaking_rate}")
    print(f"Output: {OUTPUT_DIR}")

    if args.dry_run:
        for index, text in enumerate(words, 1):
            print(f"{index:04d}. {file_name_for_text(text)}  {text}")
        return 0

    texttospeech, client = load_tts_client()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    generated = 0
    skipped = 0
    failed = 0
    manifest_items: list[tuple[str, str]] = []

    for index, text in enumerate(words, 1):
        filename = file_name_for_text(text)
        output_path = OUTPUT_DIR / filename

        if output_path.exists() and output_path.stat().st_size > 0 and not args.force:
            skipped += 1
            manifest_items.append((text, filename))
            print(f"[{index:04d}/{len(words):04d}] SKIP  {text}")
            continue

        try:
            audio = synthesize(client, texttospeech, text, args.voice, args.speaking_rate)
            if not audio:
                raise RuntimeError("Google TTS trả audio rỗng")
            output_path.write_bytes(audio)
            generated += 1
            manifest_items.append((text, filename))
            print(f"[{index:04d}/{len(words):04d}] OK    {text} -> {filename}")
        except Exception as exc:  # Tiếp tục batch để không mất các file đã render.
            failed += 1
            print(f"[{index:04d}/{len(words):04d}] ERROR {text}: {exc}", file=sys.stderr)

    write_manifest(manifest_items, args.voice, args.speaking_rate)

    print("\nHoàn tất")
    print(f"- Render mới: {generated}")
    print(f"- Bỏ qua file có sẵn: {skipped}")
    print(f"- Lỗi: {failed}")
    print(f"- Manifest: {len(manifest_items)} câu")
    print(f"- File: {MANIFEST_FILE}")

    if failed:
        print("Chạy lại cùng lệnh để tiếp tục các file còn thiếu.", file=sys.stderr)
        return 2
    return 0


def render_sample(args: argparse.Namespace) -> int:
    texttospeech, client = load_tts_client()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    sample_text = normalize_text(args.sample)
    output = OUTPUT_DIR / "_sample.mp3"
    audio = synthesize(client, texttospeech, sample_text, args.voice, args.speaking_rate)
    output.write_bytes(audio)
    print(f"Đã render sample: {sample_text}")
    print(f"Voice: {args.voice} | rate={args.speaking_rate}")
    print(f"File: {output}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Render easyWords thành MP3 Google Cloud TTS")
    parser.add_argument("--voice", default=DEFAULT_VOICE, help=f"Voice Google TTS (mặc định: {DEFAULT_VOICE})")
    parser.add_argument("--speaking-rate", type=float, default=DEFAULT_RATE, help=f"Tốc độ đọc 0.25-2.0 (mặc định: {DEFAULT_RATE})")
    parser.add_argument("--force", action="store_true", help="Render đè cả file MP3 đã tồn tại")
    parser.add_argument("--limit", type=int, default=0, help="Chỉ render N câu đầu để test")
    parser.add_argument("--only", action="append", default=[], help="Chỉ render đúng câu này; có thể dùng nhiều lần")
    parser.add_argument("--dry-run", action="store_true", help="Chỉ liệt kê file sẽ tạo, không gọi Google API")
    parser.add_argument("--list-voices", action="store_true", help="Liệt kê voice vi-VN từ Google Cloud")
    parser.add_argument("--sample", default="", help="Render một câu thử vào Audio/tts/_sample.mp3")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    try:
        if args.list_voices:
            return list_voices()
        if args.sample:
            return render_sample(args)
        return render_all(args)
    except KeyboardInterrupt:
        print("\nĐã dừng.", file=sys.stderr)
        return 130
    except Exception as exc:
        print(f"LỖI: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
